version: 2.1

jobs:

  Update-S3-Bucket: # Naming of the job to perform
    docker:
      # Select Image to run 
      - image: amazon/aws-cli # AWS docker image used to have access to aws commands pre-populated with it
    steps:
      - checkout # checking into the code - just same as we 

      # Running Normal Command You do in your Ternmmila
      - run: 
          name: Install Packages (tar) # Naming the command to run 
          command: | 
            yum install -y tar gzip

    # Deploy to S3_bucket in aws - Preview Exercise
      - run:
          name: Deploy frontend objects
          command: |
            ls -a
            cd Portfolio/page
            ls -a
            aws s3 ls
            aws s3 cp style.css s3://my-portfolio-123-lukhee
            aws s3 cp index.html s3://my-portfolio-123-lukhee
workflows:
  welcome:
    jobs:
      - Update-S3-Bucket:     
          filters:
            branches:
              only: [main] # Only Upload when the branch is in mmain branch